---
- name : play to work with lineinfile module.
#this is used to search for pattern, inseart or replace a line based on the pattern search
#this play search for pattern SELINUX in /etc/selinux/config file, and replace the same with SELINUX=disabled
  hosts: localhost
  become: true
  remote_user: ansible
  become_user: root
  tasks:
   - name: taskk to edit /etc/selinux/config file to disable selinux
     lineinfile: 
      path: /etc/selinux/config
      regexp: ^SELINUX=
      line: "SELINUX=disabled"
     #the above will search for pattern SELINUX= as beginning of the line, and replace with value given with line: attribute
...