---
- name: Create a volume group using pv /dev/sdd
  hosts: localhost
  become: true
  become_user: root
  tasks:
   - name: Create vg
     lvg:
      vg: logsvg
      pvs: /dev/sdd
      pesize: 32
   
   - name: Create a volume
     lvol:
      vg: logsvg
      lv: loglv01
      size: 512
      pvs: /dev/sdd
   
   - name: Create filesystem
     filesystem:
      fstype: xfs
      dev: /dev/logsvg/loglv01

   - name: Create mount point if it doesnt exists. Do this before it attempts to mount
     file:
      path: /logfs
      state: directory
      mode: 0755
    
   - name: Mount the filesystem
     mount:
      path: /logfs
      src: /dev/logsvg/loglv01
      fstype: xfs
      state: mounted
...